/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrokersRouteImport } from './routes/brokers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MonitoredRouteImport } from './routes/monitored'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiBrokersRouteImport } from './routes/api/brokers'
import { Route as ApiMonitoredRouteImport } from './routes/api/monitored'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as ClientLoginRouteImport } from './routes/client.$login'
import { Route as NotificationsIndexRouteImport } from './routes/notifications.index'
import { Route as NotificationsIdRouteImport } from './routes/notifications.$id'
import { Route as ApiAlertsPollRouteImport } from './routes/api/alerts/poll'
import { Route as ApiBrokersIdRouteImport } from './routes/api/brokers.$id'
import { Route as ApiNotificationsTestTelegramRouteImport } from './routes/api/notifications.test-telegram'
import { Route as ApiBrokersIdStatusRouteImport } from './routes/api/brokers.$id.status'
import { Route as ApiBrokersIdTestConnectionRouteImport } from './routes/api/brokers.$id.test-connection'
import { Route as ApiBrokersIdClientsLoginRouteImport } from './routes/api/brokers.$id.clients.$login'
import { Route as ApiBrokersIdClientsSearchRouteImport } from './routes/api/brokers.$id.clients.search'
import { Route as ApiBrokersIdClientsLoginPositionsRouteImport } from './routes/api/brokers.$id.clients.$login.positions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersRoute = BrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoredRoute = MonitoredRouteImport.update({
  id: '/monitored',
  path: '/monitored',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrokersRoute = ApiBrokersRouteImport.update({
  id: '/api/brokers',
  path: '/api/brokers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonitoredRoute = ApiMonitoredRouteImport.update({
  id: '/api/monitored',
  path: '/api/monitored',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/client/$login',
  path: '/client/$login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIdRoute = NotificationsIdRouteImport.update({
  id: '/notifications/$id',
  path: '/notifications/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsPollRoute = ApiAlertsPollRouteImport.update({
  id: '/api/alerts/poll',
  path: '/api/alerts/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrokersIdRoute = ApiBrokersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiBrokersRoute,
} as any)
const ApiNotificationsTestTelegramRoute =
  ApiNotificationsTestTelegramRouteImport.update({
    id: '/test-telegram',
    path: '/test-telegram',
    getParentRoute: () => ApiNotificationsRoute,
  } as any)
const ApiBrokersIdStatusRoute = ApiBrokersIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiBrokersIdRoute,
} as any)
const ApiBrokersIdTestConnectionRoute =
  ApiBrokersIdTestConnectionRouteImport.update({
    id: '/test-connection',
    path: '/test-connection',
    getParentRoute: () => ApiBrokersIdRoute,
  } as any)
const ApiBrokersIdClientsLoginRoute =
  ApiBrokersIdClientsLoginRouteImport.update({
    id: '/clients/$login',
    path: '/clients/$login',
    getParentRoute: () => ApiBrokersIdRoute,
  } as any)
const ApiBrokersIdClientsSearchRoute =
  ApiBrokersIdClientsSearchRouteImport.update({
    id: '/clients/search',
    path: '/clients/search',
    getParentRoute: () => ApiBrokersIdRoute,
  } as any)
const ApiBrokersIdClientsLoginPositionsRoute =
  ApiBrokersIdClientsLoginPositionsRouteImport.update({
    id: '/positions',
    path: '/positions',
    getParentRoute: () => ApiBrokersIdClientsLoginRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brokers': typeof BrokersRoute
  '/dashboard': typeof DashboardRoute
  '/monitored': typeof MonitoredRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/brokers': typeof ApiBrokersRouteWithChildren
  '/api/monitored': typeof ApiMonitoredRoute
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/session': typeof ApiSessionRoute
  '/client/$login': typeof ClientLoginRoute
  '/notifications/$id': typeof NotificationsIdRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/api/alerts/poll': typeof ApiAlertsPollRoute
  '/api/brokers/$id': typeof ApiBrokersIdRouteWithChildren
  '/api/notifications/test-telegram': typeof ApiNotificationsTestTelegramRoute
  '/api/brokers/$id/status': typeof ApiBrokersIdStatusRoute
  '/api/brokers/$id/test-connection': typeof ApiBrokersIdTestConnectionRoute
  '/api/brokers/$id/clients/$login': typeof ApiBrokersIdClientsLoginRouteWithChildren
  '/api/brokers/$id/clients/search': typeof ApiBrokersIdClientsSearchRoute
  '/api/brokers/$id/clients/$login/positions': typeof ApiBrokersIdClientsLoginPositionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brokers': typeof BrokersRoute
  '/dashboard': typeof DashboardRoute
  '/monitored': typeof MonitoredRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/brokers': typeof ApiBrokersRouteWithChildren
  '/api/monitored': typeof ApiMonitoredRoute
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/session': typeof ApiSessionRoute
  '/client/$login': typeof ClientLoginRoute
  '/notifications/$id': typeof NotificationsIdRoute
  '/notifications': typeof NotificationsIndexRoute
  '/api/alerts/poll': typeof ApiAlertsPollRoute
  '/api/brokers/$id': typeof ApiBrokersIdRouteWithChildren
  '/api/notifications/test-telegram': typeof ApiNotificationsTestTelegramRoute
  '/api/brokers/$id/status': typeof ApiBrokersIdStatusRoute
  '/api/brokers/$id/test-connection': typeof ApiBrokersIdTestConnectionRoute
  '/api/brokers/$id/clients/$login': typeof ApiBrokersIdClientsLoginRouteWithChildren
  '/api/brokers/$id/clients/search': typeof ApiBrokersIdClientsSearchRoute
  '/api/brokers/$id/clients/$login/positions': typeof ApiBrokersIdClientsLoginPositionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brokers': typeof BrokersRoute
  '/dashboard': typeof DashboardRoute
  '/monitored': typeof MonitoredRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/brokers': typeof ApiBrokersRouteWithChildren
  '/api/monitored': typeof ApiMonitoredRoute
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/session': typeof ApiSessionRoute
  '/client/$login': typeof ClientLoginRoute
  '/notifications/$id': typeof NotificationsIdRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/api/alerts/poll': typeof ApiAlertsPollRoute
  '/api/brokers/$id': typeof ApiBrokersIdRouteWithChildren
  '/api/notifications/test-telegram': typeof ApiNotificationsTestTelegramRoute
  '/api/brokers/$id/status': typeof ApiBrokersIdStatusRoute
  '/api/brokers/$id/test-connection': typeof ApiBrokersIdTestConnectionRoute
  '/api/brokers/$id/clients/$login': typeof ApiBrokersIdClientsLoginRouteWithChildren
  '/api/brokers/$id/clients/search': typeof ApiBrokersIdClientsSearchRoute
  '/api/brokers/$id/clients/$login/positions': typeof ApiBrokersIdClientsLoginPositionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brokers'
    | '/dashboard'
    | '/monitored'
    | '/search'
    | '/settings'
    | '/api/brokers'
    | '/api/monitored'
    | '/api/notifications'
    | '/api/session'
    | '/client/$login'
    | '/notifications/$id'
    | '/notifications/'
    | '/api/alerts/poll'
    | '/api/brokers/$id'
    | '/api/notifications/test-telegram'
    | '/api/brokers/$id/status'
    | '/api/brokers/$id/test-connection'
    | '/api/brokers/$id/clients/$login'
    | '/api/brokers/$id/clients/search'
    | '/api/brokers/$id/clients/$login/positions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brokers'
    | '/dashboard'
    | '/monitored'
    | '/search'
    | '/settings'
    | '/api/brokers'
    | '/api/monitored'
    | '/api/notifications'
    | '/api/session'
    | '/client/$login'
    | '/notifications/$id'
    | '/notifications'
    | '/api/alerts/poll'
    | '/api/brokers/$id'
    | '/api/notifications/test-telegram'
    | '/api/brokers/$id/status'
    | '/api/brokers/$id/test-connection'
    | '/api/brokers/$id/clients/$login'
    | '/api/brokers/$id/clients/search'
    | '/api/brokers/$id/clients/$login/positions'
  id:
    | '__root__'
    | '/'
    | '/brokers'
    | '/dashboard'
    | '/monitored'
    | '/search'
    | '/settings'
    | '/api/brokers'
    | '/api/monitored'
    | '/api/notifications'
    | '/api/session'
    | '/client/$login'
    | '/notifications/$id'
    | '/notifications/'
    | '/api/alerts/poll'
    | '/api/brokers/$id'
    | '/api/notifications/test-telegram'
    | '/api/brokers/$id/status'
    | '/api/brokers/$id/test-connection'
    | '/api/brokers/$id/clients/$login'
    | '/api/brokers/$id/clients/search'
    | '/api/brokers/$id/clients/$login/positions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrokersRoute: typeof BrokersRoute
  DashboardRoute: typeof DashboardRoute
  MonitoredRoute: typeof MonitoredRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ApiBrokersRoute: typeof ApiBrokersRouteWithChildren
  ApiMonitoredRoute: typeof ApiMonitoredRoute
  ApiNotificationsRoute: typeof ApiNotificationsRouteWithChildren
  ApiSessionRoute: typeof ApiSessionRoute
  ClientLoginRoute: typeof ClientLoginRoute
  NotificationsIdRoute: typeof NotificationsIdRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  ApiAlertsPollRoute: typeof ApiAlertsPollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers': {
      id: '/brokers'
      path: '/brokers'
      fullPath: '/brokers'
      preLoaderRoute: typeof BrokersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitored': {
      id: '/monitored'
      path: '/monitored'
      fullPath: '/monitored'
      preLoaderRoute: typeof MonitoredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brokers': {
      id: '/api/brokers'
      path: '/api/brokers'
      fullPath: '/api/brokers'
      preLoaderRoute: typeof ApiBrokersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monitored': {
      id: '/api/monitored'
      path: '/api/monitored'
      fullPath: '/api/monitored'
      preLoaderRoute: typeof ApiMonitoredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/$login': {
      id: '/client/$login'
      path: '/client/$login'
      fullPath: '/client/$login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/$id': {
      id: '/notifications/$id'
      path: '/notifications/$id'
      fullPath: '/notifications/$id'
      preLoaderRoute: typeof NotificationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts/poll': {
      id: '/api/alerts/poll'
      path: '/api/alerts/poll'
      fullPath: '/api/alerts/poll'
      preLoaderRoute: typeof ApiAlertsPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brokers/$id': {
      id: '/api/brokers/$id'
      path: '/$id'
      fullPath: '/api/brokers/$id'
      preLoaderRoute: typeof ApiBrokersIdRouteImport
      parentRoute: typeof ApiBrokersRoute
    }
    '/api/notifications/test-telegram': {
      id: '/api/notifications/test-telegram'
      path: '/test-telegram'
      fullPath: '/api/notifications/test-telegram'
      preLoaderRoute: typeof ApiNotificationsTestTelegramRouteImport
      parentRoute: typeof ApiNotificationsRoute
    }
    '/api/brokers/$id/status': {
      id: '/api/brokers/$id/status'
      path: '/status'
      fullPath: '/api/brokers/$id/status'
      preLoaderRoute: typeof ApiBrokersIdStatusRouteImport
      parentRoute: typeof ApiBrokersIdRoute
    }
    '/api/brokers/$id/test-connection': {
      id: '/api/brokers/$id/test-connection'
      path: '/test-connection'
      fullPath: '/api/brokers/$id/test-connection'
      preLoaderRoute: typeof ApiBrokersIdTestConnectionRouteImport
      parentRoute: typeof ApiBrokersIdRoute
    }
    '/api/brokers/$id/clients/$login': {
      id: '/api/brokers/$id/clients/$login'
      path: '/clients/$login'
      fullPath: '/api/brokers/$id/clients/$login'
      preLoaderRoute: typeof ApiBrokersIdClientsLoginRouteImport
      parentRoute: typeof ApiBrokersIdRoute
    }
    '/api/brokers/$id/clients/search': {
      id: '/api/brokers/$id/clients/search'
      path: '/clients/search'
      fullPath: '/api/brokers/$id/clients/search'
      preLoaderRoute: typeof ApiBrokersIdClientsSearchRouteImport
      parentRoute: typeof ApiBrokersIdRoute
    }
    '/api/brokers/$id/clients/$login/positions': {
      id: '/api/brokers/$id/clients/$login/positions'
      path: '/positions'
      fullPath: '/api/brokers/$id/clients/$login/positions'
      preLoaderRoute: typeof ApiBrokersIdClientsLoginPositionsRouteImport
      parentRoute: typeof ApiBrokersIdClientsLoginRoute
    }
  }
}

interface ApiBrokersIdClientsLoginRouteChildren {
  ApiBrokersIdClientsLoginPositionsRoute: typeof ApiBrokersIdClientsLoginPositionsRoute
}

const ApiBrokersIdClientsLoginRouteChildren: ApiBrokersIdClientsLoginRouteChildren =
  {
    ApiBrokersIdClientsLoginPositionsRoute:
      ApiBrokersIdClientsLoginPositionsRoute,
  }

const ApiBrokersIdClientsLoginRouteWithChildren =
  ApiBrokersIdClientsLoginRoute._addFileChildren(
    ApiBrokersIdClientsLoginRouteChildren,
  )

interface ApiBrokersIdRouteChildren {
  ApiBrokersIdStatusRoute: typeof ApiBrokersIdStatusRoute
  ApiBrokersIdTestConnectionRoute: typeof ApiBrokersIdTestConnectionRoute
  ApiBrokersIdClientsLoginRoute: typeof ApiBrokersIdClientsLoginRouteWithChildren
  ApiBrokersIdClientsSearchRoute: typeof ApiBrokersIdClientsSearchRoute
}

const ApiBrokersIdRouteChildren: ApiBrokersIdRouteChildren = {
  ApiBrokersIdStatusRoute: ApiBrokersIdStatusRoute,
  ApiBrokersIdTestConnectionRoute: ApiBrokersIdTestConnectionRoute,
  ApiBrokersIdClientsLoginRoute: ApiBrokersIdClientsLoginRouteWithChildren,
  ApiBrokersIdClientsSearchRoute: ApiBrokersIdClientsSearchRoute,
}

const ApiBrokersIdRouteWithChildren = ApiBrokersIdRoute._addFileChildren(
  ApiBrokersIdRouteChildren,
)

interface ApiBrokersRouteChildren {
  ApiBrokersIdRoute: typeof ApiBrokersIdRouteWithChildren
}

const ApiBrokersRouteChildren: ApiBrokersRouteChildren = {
  ApiBrokersIdRoute: ApiBrokersIdRouteWithChildren,
}

const ApiBrokersRouteWithChildren = ApiBrokersRoute._addFileChildren(
  ApiBrokersRouteChildren,
)

interface ApiNotificationsRouteChildren {
  ApiNotificationsTestTelegramRoute: typeof ApiNotificationsTestTelegramRoute
}

const ApiNotificationsRouteChildren: ApiNotificationsRouteChildren = {
  ApiNotificationsTestTelegramRoute: ApiNotificationsTestTelegramRoute,
}

const ApiNotificationsRouteWithChildren =
  ApiNotificationsRoute._addFileChildren(ApiNotificationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrokersRoute: BrokersRoute,
  DashboardRoute: DashboardRoute,
  MonitoredRoute: MonitoredRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ApiBrokersRoute: ApiBrokersRouteWithChildren,
  ApiMonitoredRoute: ApiMonitoredRoute,
  ApiNotificationsRoute: ApiNotificationsRouteWithChildren,
  ApiSessionRoute: ApiSessionRoute,
  ClientLoginRoute: ClientLoginRoute,
  NotificationsIdRoute: NotificationsIdRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  ApiAlertsPollRoute: ApiAlertsPollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
