/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrokersRouteImport } from './routes/brokers'
import { Route as CopierRouteImport } from './routes/copier'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MonitoredRouteImport } from './routes/monitored'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdminBrokersRouteImport } from './routes/admin.brokers'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminMonitoredRouteImport } from './routes/admin.monitored'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as ApiBrokersRouteImport } from './routes/api/brokers'
import { Route as ApiCopierRouteImport } from './routes/api/copier'
import { Route as ApiMonitoredRouteImport } from './routes/api/monitored'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as ClientLoginRouteImport } from './routes/client.$login'
import { Route as NotificationsIndexRouteImport } from './routes/notifications.index'
import { Route as NotificationsIdRouteImport } from './routes/notifications.$id'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'
import { Route as ApiAdminBrokersRouteImport } from './routes/api/admin/brokers'
import { Route as ApiAdminLogsRouteImport } from './routes/api/admin/logs'
import { Route as ApiAdminMonitoredRouteImport } from './routes/api/admin/monitored'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAlertsPollRouteImport } from './routes/api/alerts/poll'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth.me'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth.signup'
import { Route as ApiBrokersIdRouteImport } from './routes/api/brokers.$id'
import { Route as ApiCopierAccountsRouteImport } from './routes/api/copier.accounts'
import { Route as ApiCopierLinksRouteImport } from './routes/api/copier.links'
import { Route as ApiNotificationsTestTelegramRouteImport } from './routes/api/notifications.test-telegram'
import { Route as ApiAdminUsersIdRouteImport } from './routes/api/admin/users.$id'
import { Route as ApiBrokersIdStatusRouteImport } from './routes/api/brokers.$id.status'
import { Route as ApiBrokersIdTestConnectionRouteImport } from './routes/api/brokers.$id.test-connection'
import { Route as ApiCopierAccountsIdRouteImport } from './routes/api/copier.accounts.$id'
import { Route as ApiCopierLinksIdRouteImport } from './routes/api/copier.links.$id'
import { Route as ApiAdminUsersIdLimitsRouteImport } from './routes/api/admin/users.$id.limits'
import { Route as ApiAdminUsersIdPermissionsRouteImport } from './routes/api/admin/users.$id.permissions'
import { Route as ApiAdminUsersIdStatusRouteImport } from './routes/api/admin/users.$id.status'
import { Route as ApiBrokersIdClientsLoginRouteImport } from './routes/api/brokers.$id.clients.$login'
import { Route as ApiBrokersIdClientsSearchRouteImport } from './routes/api/brokers.$id.clients.search'
import { Route as ApiCopierAccountsIdProbeRouteImport } from './routes/api/copier.accounts.$id.probe'
import { Route as ApiCopierAccountsIdSymbolsRouteImport } from './routes/api/copier.accounts.$id.symbols'
import { Route as ApiCopierLinksIdArmRouteImport } from './routes/api/copier.links.$id.arm'
import { Route as ApiCopierLinksIdFlattenRouteImport } from './routes/api/copier.links.$id.flatten'
import { Route as ApiCopierLinksIdPreviewRouteImport } from './routes/api/copier.links.$id.preview'
import { Route as ApiBrokersIdClientsLoginPositionsRouteImport } from './routes/api/brokers.$id.clients.$login.positions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersRoute = BrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => rootRouteImport,
} as any)
const CopierRoute = CopierRouteImport.update({
  id: '/copier',
  path: '/copier',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoredRoute = MonitoredRouteImport.update({
  id: '/monitored',
  path: '/monitored',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrokersRoute = AdminBrokersRouteImport.update({
  id: '/admin/brokers',
  path: '/admin/brokers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMonitoredRoute = AdminMonitoredRouteImport.update({
  id: '/admin/monitored',
  path: '/admin/monitored',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrokersRoute = ApiBrokersRouteImport.update({
  id: '/api/brokers',
  path: '/api/brokers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopierRoute = ApiCopierRouteImport.update({
  id: '/api/copier',
  path: '/api/copier',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonitoredRoute = ApiMonitoredRouteImport.update({
  id: '/api/monitored',
  path: '/api/monitored',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/client/$login',
  path: '/client/$login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIdRoute = NotificationsIdRouteImport.update({
  id: '/notifications/$id',
  path: '/notifications/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/admin/users/$id',
  path: '/admin/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBrokersRoute = ApiAdminBrokersRouteImport.update({
  id: '/api/admin/brokers',
  path: '/api/admin/brokers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogsRoute = ApiAdminLogsRouteImport.update({
  id: '/api/admin/logs',
  path: '/api/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMonitoredRoute = ApiAdminMonitoredRouteImport.update({
  id: '/api/admin/monitored',
  path: '/api/admin/monitored',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsPollRoute = ApiAlertsPollRouteImport.update({
  id: '/api/alerts/poll',
  path: '/api/alerts/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrokersIdRoute = ApiBrokersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiBrokersRoute,
} as any)
const ApiCopierAccountsRoute = ApiCopierAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => ApiCopierRoute,
} as any)
const ApiCopierLinksRoute = ApiCopierLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => ApiCopierRoute,
} as any)
const ApiNotificationsTestTelegramRoute =
  ApiNotificationsTestTelegramRouteImport.update({
    id: '/test-telegram',
    path: '/test-telegram',
    getParentRoute: () => ApiNotificationsRoute,
  } as any)
const ApiAdminUsersIdRoute = ApiAdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminUsersRoute,
} as any)
const ApiBrokersIdStatusRoute = ApiBrokersIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiBrokersIdRoute,
} as any)
const ApiBrokersIdTestConnectionRoute =
  ApiBrokersIdTestConnectionRouteImport.update({
    id: '/test-connection',
    path: '/test-connection',
    getParentRoute: () => ApiBrokersIdRoute,
  } as any)
const ApiCopierAccountsIdRoute = ApiCopierAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCopierAccountsRoute,
} as any)
const ApiCopierLinksIdRoute = ApiCopierLinksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCopierLinksRoute,
} as any)
const ApiAdminUsersIdLimitsRoute = ApiAdminUsersIdLimitsRouteImport.update({
  id: '/limits',
  path: '/limits',
  getParentRoute: () => ApiAdminUsersIdRoute,
} as any)
const ApiAdminUsersIdPermissionsRoute =
  ApiAdminUsersIdPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => ApiAdminUsersIdRoute,
  } as any)
const ApiAdminUsersIdStatusRoute = ApiAdminUsersIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiAdminUsersIdRoute,
} as any)
const ApiBrokersIdClientsLoginRoute =
  ApiBrokersIdClientsLoginRouteImport.update({
    id: '/clients/$login',
    path: '/clients/$login',
    getParentRoute: () => ApiBrokersIdRoute,
  } as any)
const ApiBrokersIdClientsSearchRoute =
  ApiBrokersIdClientsSearchRouteImport.update({
    id: '/clients/search',
    path: '/clients/search',
    getParentRoute: () => ApiBrokersIdRoute,
  } as any)
const ApiCopierAccountsIdProbeRoute =
  ApiCopierAccountsIdProbeRouteImport.update({
    id: '/probe',
    path: '/probe',
    getParentRoute: () => ApiCopierAccountsIdRoute,
  } as any)
const ApiCopierAccountsIdSymbolsRoute =
  ApiCopierAccountsIdSymbolsRouteImport.update({
    id: '/symbols',
    path: '/symbols',
    getParentRoute: () => ApiCopierAccountsIdRoute,
  } as any)
const ApiCopierLinksIdArmRoute = ApiCopierLinksIdArmRouteImport.update({
  id: '/arm',
  path: '/arm',
  getParentRoute: () => ApiCopierLinksIdRoute,
} as any)
const ApiCopierLinksIdFlattenRoute = ApiCopierLinksIdFlattenRouteImport.update({
  id: '/flatten',
  path: '/flatten',
  getParentRoute: () => ApiCopierLinksIdRoute,
} as any)
const ApiCopierLinksIdPreviewRoute = ApiCopierLinksIdPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ApiCopierLinksIdRoute,
} as any)
const ApiBrokersIdClientsLoginPositionsRoute =
  ApiBrokersIdClientsLoginPositionsRouteImport.update({
    id: '/positions',
    path: '/positions',
    getParentRoute: () => ApiBrokersIdClientsLoginRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brokers': typeof BrokersRoute
  '/copier': typeof CopierRoute
  '/dashboard': typeof DashboardRoute
  '/monitored': typeof MonitoredRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/brokers': typeof AdminBrokersRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/monitored': typeof AdminMonitoredRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/brokers': typeof ApiBrokersRouteWithChildren
  '/api/copier': typeof ApiCopierRouteWithChildren
  '/api/monitored': typeof ApiMonitoredRoute
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/session': typeof ApiSessionRoute
  '/client/$login': typeof ClientLoginRoute
  '/notifications/$id': typeof NotificationsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/admin/brokers': typeof ApiAdminBrokersRoute
  '/api/admin/logs': typeof ApiAdminLogsRoute
  '/api/admin/monitored': typeof ApiAdminMonitoredRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/alerts/poll': typeof ApiAlertsPollRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/brokers/$id': typeof ApiBrokersIdRouteWithChildren
  '/api/copier/accounts': typeof ApiCopierAccountsRouteWithChildren
  '/api/copier/links': typeof ApiCopierLinksRouteWithChildren
  '/api/notifications/test-telegram': typeof ApiNotificationsTestTelegramRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRouteWithChildren
  '/api/brokers/$id/status': typeof ApiBrokersIdStatusRoute
  '/api/brokers/$id/test-connection': typeof ApiBrokersIdTestConnectionRoute
  '/api/copier/accounts/$id': typeof ApiCopierAccountsIdRouteWithChildren
  '/api/copier/links/$id': typeof ApiCopierLinksIdRouteWithChildren
  '/api/admin/users/$id/limits': typeof ApiAdminUsersIdLimitsRoute
  '/api/admin/users/$id/permissions': typeof ApiAdminUsersIdPermissionsRoute
  '/api/admin/users/$id/status': typeof ApiAdminUsersIdStatusRoute
  '/api/brokers/$id/clients/$login': typeof ApiBrokersIdClientsLoginRouteWithChildren
  '/api/brokers/$id/clients/search': typeof ApiBrokersIdClientsSearchRoute
  '/api/copier/accounts/$id/probe': typeof ApiCopierAccountsIdProbeRoute
  '/api/copier/accounts/$id/symbols': typeof ApiCopierAccountsIdSymbolsRoute
  '/api/copier/links/$id/arm': typeof ApiCopierLinksIdArmRoute
  '/api/copier/links/$id/flatten': typeof ApiCopierLinksIdFlattenRoute
  '/api/copier/links/$id/preview': typeof ApiCopierLinksIdPreviewRoute
  '/api/brokers/$id/clients/$login/positions': typeof ApiBrokersIdClientsLoginPositionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brokers': typeof BrokersRoute
  '/copier': typeof CopierRoute
  '/dashboard': typeof DashboardRoute
  '/monitored': typeof MonitoredRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/brokers': typeof AdminBrokersRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/monitored': typeof AdminMonitoredRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/brokers': typeof ApiBrokersRouteWithChildren
  '/api/copier': typeof ApiCopierRouteWithChildren
  '/api/monitored': typeof ApiMonitoredRoute
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/session': typeof ApiSessionRoute
  '/client/$login': typeof ClientLoginRoute
  '/notifications/$id': typeof NotificationsIdRoute
  '/admin': typeof AdminIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/admin/brokers': typeof ApiAdminBrokersRoute
  '/api/admin/logs': typeof ApiAdminLogsRoute
  '/api/admin/monitored': typeof ApiAdminMonitoredRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/alerts/poll': typeof ApiAlertsPollRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/brokers/$id': typeof ApiBrokersIdRouteWithChildren
  '/api/copier/accounts': typeof ApiCopierAccountsRouteWithChildren
  '/api/copier/links': typeof ApiCopierLinksRouteWithChildren
  '/api/notifications/test-telegram': typeof ApiNotificationsTestTelegramRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRouteWithChildren
  '/api/brokers/$id/status': typeof ApiBrokersIdStatusRoute
  '/api/brokers/$id/test-connection': typeof ApiBrokersIdTestConnectionRoute
  '/api/copier/accounts/$id': typeof ApiCopierAccountsIdRouteWithChildren
  '/api/copier/links/$id': typeof ApiCopierLinksIdRouteWithChildren
  '/api/admin/users/$id/limits': typeof ApiAdminUsersIdLimitsRoute
  '/api/admin/users/$id/permissions': typeof ApiAdminUsersIdPermissionsRoute
  '/api/admin/users/$id/status': typeof ApiAdminUsersIdStatusRoute
  '/api/brokers/$id/clients/$login': typeof ApiBrokersIdClientsLoginRouteWithChildren
  '/api/brokers/$id/clients/search': typeof ApiBrokersIdClientsSearchRoute
  '/api/copier/accounts/$id/probe': typeof ApiCopierAccountsIdProbeRoute
  '/api/copier/accounts/$id/symbols': typeof ApiCopierAccountsIdSymbolsRoute
  '/api/copier/links/$id/arm': typeof ApiCopierLinksIdArmRoute
  '/api/copier/links/$id/flatten': typeof ApiCopierLinksIdFlattenRoute
  '/api/copier/links/$id/preview': typeof ApiCopierLinksIdPreviewRoute
  '/api/brokers/$id/clients/$login/positions': typeof ApiBrokersIdClientsLoginPositionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brokers': typeof BrokersRoute
  '/copier': typeof CopierRoute
  '/dashboard': typeof DashboardRoute
  '/monitored': typeof MonitoredRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/brokers': typeof AdminBrokersRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/monitored': typeof AdminMonitoredRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/brokers': typeof ApiBrokersRouteWithChildren
  '/api/copier': typeof ApiCopierRouteWithChildren
  '/api/monitored': typeof ApiMonitoredRoute
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/session': typeof ApiSessionRoute
  '/client/$login': typeof ClientLoginRoute
  '/notifications/$id': typeof NotificationsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/admin/brokers': typeof ApiAdminBrokersRoute
  '/api/admin/logs': typeof ApiAdminLogsRoute
  '/api/admin/monitored': typeof ApiAdminMonitoredRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/alerts/poll': typeof ApiAlertsPollRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/brokers/$id': typeof ApiBrokersIdRouteWithChildren
  '/api/copier/accounts': typeof ApiCopierAccountsRouteWithChildren
  '/api/copier/links': typeof ApiCopierLinksRouteWithChildren
  '/api/notifications/test-telegram': typeof ApiNotificationsTestTelegramRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRouteWithChildren
  '/api/brokers/$id/status': typeof ApiBrokersIdStatusRoute
  '/api/brokers/$id/test-connection': typeof ApiBrokersIdTestConnectionRoute
  '/api/copier/accounts/$id': typeof ApiCopierAccountsIdRouteWithChildren
  '/api/copier/links/$id': typeof ApiCopierLinksIdRouteWithChildren
  '/api/admin/users/$id/limits': typeof ApiAdminUsersIdLimitsRoute
  '/api/admin/users/$id/permissions': typeof ApiAdminUsersIdPermissionsRoute
  '/api/admin/users/$id/status': typeof ApiAdminUsersIdStatusRoute
  '/api/brokers/$id/clients/$login': typeof ApiBrokersIdClientsLoginRouteWithChildren
  '/api/brokers/$id/clients/search': typeof ApiBrokersIdClientsSearchRoute
  '/api/copier/accounts/$id/probe': typeof ApiCopierAccountsIdProbeRoute
  '/api/copier/accounts/$id/symbols': typeof ApiCopierAccountsIdSymbolsRoute
  '/api/copier/links/$id/arm': typeof ApiCopierLinksIdArmRoute
  '/api/copier/links/$id/flatten': typeof ApiCopierLinksIdFlattenRoute
  '/api/copier/links/$id/preview': typeof ApiCopierLinksIdPreviewRoute
  '/api/brokers/$id/clients/$login/positions': typeof ApiBrokersIdClientsLoginPositionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brokers'
    | '/copier'
    | '/dashboard'
    | '/monitored'
    | '/search'
    | '/settings'
    | '/admin/approvals'
    | '/admin/brokers'
    | '/admin/logs'
    | '/admin/monitored'
    | '/admin/settings'
    | '/api/brokers'
    | '/api/copier'
    | '/api/monitored'
    | '/api/notifications'
    | '/api/session'
    | '/client/$login'
    | '/notifications/$id'
    | '/admin/'
    | '/notifications/'
    | '/admin/users/$id'
    | '/api/admin/brokers'
    | '/api/admin/logs'
    | '/api/admin/monitored'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/alerts/poll'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/brokers/$id'
    | '/api/copier/accounts'
    | '/api/copier/links'
    | '/api/notifications/test-telegram'
    | '/admin/users/'
    | '/api/admin/users/$id'
    | '/api/brokers/$id/status'
    | '/api/brokers/$id/test-connection'
    | '/api/copier/accounts/$id'
    | '/api/copier/links/$id'
    | '/api/admin/users/$id/limits'
    | '/api/admin/users/$id/permissions'
    | '/api/admin/users/$id/status'
    | '/api/brokers/$id/clients/$login'
    | '/api/brokers/$id/clients/search'
    | '/api/copier/accounts/$id/probe'
    | '/api/copier/accounts/$id/symbols'
    | '/api/copier/links/$id/arm'
    | '/api/copier/links/$id/flatten'
    | '/api/copier/links/$id/preview'
    | '/api/brokers/$id/clients/$login/positions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brokers'
    | '/copier'
    | '/dashboard'
    | '/monitored'
    | '/search'
    | '/settings'
    | '/admin/approvals'
    | '/admin/brokers'
    | '/admin/logs'
    | '/admin/monitored'
    | '/admin/settings'
    | '/api/brokers'
    | '/api/copier'
    | '/api/monitored'
    | '/api/notifications'
    | '/api/session'
    | '/client/$login'
    | '/notifications/$id'
    | '/admin'
    | '/notifications'
    | '/admin/users/$id'
    | '/api/admin/brokers'
    | '/api/admin/logs'
    | '/api/admin/monitored'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/alerts/poll'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/brokers/$id'
    | '/api/copier/accounts'
    | '/api/copier/links'
    | '/api/notifications/test-telegram'
    | '/admin/users'
    | '/api/admin/users/$id'
    | '/api/brokers/$id/status'
    | '/api/brokers/$id/test-connection'
    | '/api/copier/accounts/$id'
    | '/api/copier/links/$id'
    | '/api/admin/users/$id/limits'
    | '/api/admin/users/$id/permissions'
    | '/api/admin/users/$id/status'
    | '/api/brokers/$id/clients/$login'
    | '/api/brokers/$id/clients/search'
    | '/api/copier/accounts/$id/probe'
    | '/api/copier/accounts/$id/symbols'
    | '/api/copier/links/$id/arm'
    | '/api/copier/links/$id/flatten'
    | '/api/copier/links/$id/preview'
    | '/api/brokers/$id/clients/$login/positions'
  id:
    | '__root__'
    | '/'
    | '/brokers'
    | '/copier'
    | '/dashboard'
    | '/monitored'
    | '/search'
    | '/settings'
    | '/admin/approvals'
    | '/admin/brokers'
    | '/admin/logs'
    | '/admin/monitored'
    | '/admin/settings'
    | '/api/brokers'
    | '/api/copier'
    | '/api/monitored'
    | '/api/notifications'
    | '/api/session'
    | '/client/$login'
    | '/notifications/$id'
    | '/admin/'
    | '/notifications/'
    | '/admin/users/$id'
    | '/api/admin/brokers'
    | '/api/admin/logs'
    | '/api/admin/monitored'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/alerts/poll'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/brokers/$id'
    | '/api/copier/accounts'
    | '/api/copier/links'
    | '/api/notifications/test-telegram'
    | '/admin/users/'
    | '/api/admin/users/$id'
    | '/api/brokers/$id/status'
    | '/api/brokers/$id/test-connection'
    | '/api/copier/accounts/$id'
    | '/api/copier/links/$id'
    | '/api/admin/users/$id/limits'
    | '/api/admin/users/$id/permissions'
    | '/api/admin/users/$id/status'
    | '/api/brokers/$id/clients/$login'
    | '/api/brokers/$id/clients/search'
    | '/api/copier/accounts/$id/probe'
    | '/api/copier/accounts/$id/symbols'
    | '/api/copier/links/$id/arm'
    | '/api/copier/links/$id/flatten'
    | '/api/copier/links/$id/preview'
    | '/api/brokers/$id/clients/$login/positions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrokersRoute: typeof BrokersRoute
  CopierRoute: typeof CopierRoute
  DashboardRoute: typeof DashboardRoute
  MonitoredRoute: typeof MonitoredRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminBrokersRoute: typeof AdminBrokersRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMonitoredRoute: typeof AdminMonitoredRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  ApiBrokersRoute: typeof ApiBrokersRouteWithChildren
  ApiCopierRoute: typeof ApiCopierRouteWithChildren
  ApiMonitoredRoute: typeof ApiMonitoredRoute
  ApiNotificationsRoute: typeof ApiNotificationsRouteWithChildren
  ApiSessionRoute: typeof ApiSessionRoute
  ClientLoginRoute: typeof ClientLoginRoute
  NotificationsIdRoute: typeof NotificationsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  ApiAdminBrokersRoute: typeof ApiAdminBrokersRoute
  ApiAdminLogsRoute: typeof ApiAdminLogsRoute
  ApiAdminMonitoredRoute: typeof ApiAdminMonitoredRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRouteWithChildren
  ApiAlertsPollRoute: typeof ApiAlertsPollRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers': {
      id: '/brokers'
      path: '/brokers'
      fullPath: '/brokers'
      preLoaderRoute: typeof BrokersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copier': {
      id: '/copier'
      path: '/copier'
      fullPath: '/copier'
      preLoaderRoute: typeof CopierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitored': {
      id: '/monitored'
      path: '/monitored'
      fullPath: '/monitored'
      preLoaderRoute: typeof MonitoredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/brokers': {
      id: '/admin/brokers'
      path: '/admin/brokers'
      fullPath: '/admin/brokers'
      preLoaderRoute: typeof AdminBrokersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/monitored': {
      id: '/admin/monitored'
      path: '/admin/monitored'
      fullPath: '/admin/monitored'
      preLoaderRoute: typeof AdminMonitoredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brokers': {
      id: '/api/brokers'
      path: '/api/brokers'
      fullPath: '/api/brokers'
      preLoaderRoute: typeof ApiBrokersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copier': {
      id: '/api/copier'
      path: '/api/copier'
      fullPath: '/api/copier'
      preLoaderRoute: typeof ApiCopierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monitored': {
      id: '/api/monitored'
      path: '/api/monitored'
      fullPath: '/api/monitored'
      preLoaderRoute: typeof ApiMonitoredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/$login': {
      id: '/client/$login'
      path: '/client/$login'
      fullPath: '/client/$login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/$id': {
      id: '/notifications/$id'
      path: '/notifications/$id'
      fullPath: '/notifications/$id'
      preLoaderRoute: typeof NotificationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/brokers': {
      id: '/api/admin/brokers'
      path: '/api/admin/brokers'
      fullPath: '/api/admin/brokers'
      preLoaderRoute: typeof ApiAdminBrokersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logs': {
      id: '/api/admin/logs'
      path: '/api/admin/logs'
      fullPath: '/api/admin/logs'
      preLoaderRoute: typeof ApiAdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/monitored': {
      id: '/api/admin/monitored'
      path: '/api/admin/monitored'
      fullPath: '/api/admin/monitored'
      preLoaderRoute: typeof ApiAdminMonitoredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts/poll': {
      id: '/api/alerts/poll'
      path: '/api/alerts/poll'
      fullPath: '/api/alerts/poll'
      preLoaderRoute: typeof ApiAlertsPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brokers/$id': {
      id: '/api/brokers/$id'
      path: '/$id'
      fullPath: '/api/brokers/$id'
      preLoaderRoute: typeof ApiBrokersIdRouteImport
      parentRoute: typeof ApiBrokersRoute
    }
    '/api/copier/accounts': {
      id: '/api/copier/accounts'
      path: '/accounts'
      fullPath: '/api/copier/accounts'
      preLoaderRoute: typeof ApiCopierAccountsRouteImport
      parentRoute: typeof ApiCopierRoute
    }
    '/api/copier/links': {
      id: '/api/copier/links'
      path: '/links'
      fullPath: '/api/copier/links'
      preLoaderRoute: typeof ApiCopierLinksRouteImport
      parentRoute: typeof ApiCopierRoute
    }
    '/api/notifications/test-telegram': {
      id: '/api/notifications/test-telegram'
      path: '/test-telegram'
      fullPath: '/api/notifications/test-telegram'
      preLoaderRoute: typeof ApiNotificationsTestTelegramRouteImport
      parentRoute: typeof ApiNotificationsRoute
    }
    '/api/admin/users/$id': {
      id: '/api/admin/users/$id'
      path: '/$id'
      fullPath: '/api/admin/users/$id'
      preLoaderRoute: typeof ApiAdminUsersIdRouteImport
      parentRoute: typeof ApiAdminUsersRoute
    }
    '/api/brokers/$id/status': {
      id: '/api/brokers/$id/status'
      path: '/status'
      fullPath: '/api/brokers/$id/status'
      preLoaderRoute: typeof ApiBrokersIdStatusRouteImport
      parentRoute: typeof ApiBrokersIdRoute
    }
    '/api/brokers/$id/test-connection': {
      id: '/api/brokers/$id/test-connection'
      path: '/test-connection'
      fullPath: '/api/brokers/$id/test-connection'
      preLoaderRoute: typeof ApiBrokersIdTestConnectionRouteImport
      parentRoute: typeof ApiBrokersIdRoute
    }
    '/api/copier/accounts/$id': {
      id: '/api/copier/accounts/$id'
      path: '/$id'
      fullPath: '/api/copier/accounts/$id'
      preLoaderRoute: typeof ApiCopierAccountsIdRouteImport
      parentRoute: typeof ApiCopierAccountsRoute
    }
    '/api/copier/links/$id': {
      id: '/api/copier/links/$id'
      path: '/$id'
      fullPath: '/api/copier/links/$id'
      preLoaderRoute: typeof ApiCopierLinksIdRouteImport
      parentRoute: typeof ApiCopierLinksRoute
    }
    '/api/admin/users/$id/limits': {
      id: '/api/admin/users/$id/limits'
      path: '/limits'
      fullPath: '/api/admin/users/$id/limits'
      preLoaderRoute: typeof ApiAdminUsersIdLimitsRouteImport
      parentRoute: typeof ApiAdminUsersIdRoute
    }
    '/api/admin/users/$id/permissions': {
      id: '/api/admin/users/$id/permissions'
      path: '/permissions'
      fullPath: '/api/admin/users/$id/permissions'
      preLoaderRoute: typeof ApiAdminUsersIdPermissionsRouteImport
      parentRoute: typeof ApiAdminUsersIdRoute
    }
    '/api/admin/users/$id/status': {
      id: '/api/admin/users/$id/status'
      path: '/status'
      fullPath: '/api/admin/users/$id/status'
      preLoaderRoute: typeof ApiAdminUsersIdStatusRouteImport
      parentRoute: typeof ApiAdminUsersIdRoute
    }
    '/api/brokers/$id/clients/$login': {
      id: '/api/brokers/$id/clients/$login'
      path: '/clients/$login'
      fullPath: '/api/brokers/$id/clients/$login'
      preLoaderRoute: typeof ApiBrokersIdClientsLoginRouteImport
      parentRoute: typeof ApiBrokersIdRoute
    }
    '/api/brokers/$id/clients/search': {
      id: '/api/brokers/$id/clients/search'
      path: '/clients/search'
      fullPath: '/api/brokers/$id/clients/search'
      preLoaderRoute: typeof ApiBrokersIdClientsSearchRouteImport
      parentRoute: typeof ApiBrokersIdRoute
    }
    '/api/copier/accounts/$id/probe': {
      id: '/api/copier/accounts/$id/probe'
      path: '/probe'
      fullPath: '/api/copier/accounts/$id/probe'
      preLoaderRoute: typeof ApiCopierAccountsIdProbeRouteImport
      parentRoute: typeof ApiCopierAccountsIdRoute
    }
    '/api/copier/accounts/$id/symbols': {
      id: '/api/copier/accounts/$id/symbols'
      path: '/symbols'
      fullPath: '/api/copier/accounts/$id/symbols'
      preLoaderRoute: typeof ApiCopierAccountsIdSymbolsRouteImport
      parentRoute: typeof ApiCopierAccountsIdRoute
    }
    '/api/copier/links/$id/arm': {
      id: '/api/copier/links/$id/arm'
      path: '/arm'
      fullPath: '/api/copier/links/$id/arm'
      preLoaderRoute: typeof ApiCopierLinksIdArmRouteImport
      parentRoute: typeof ApiCopierLinksIdRoute
    }
    '/api/copier/links/$id/flatten': {
      id: '/api/copier/links/$id/flatten'
      path: '/flatten'
      fullPath: '/api/copier/links/$id/flatten'
      preLoaderRoute: typeof ApiCopierLinksIdFlattenRouteImport
      parentRoute: typeof ApiCopierLinksIdRoute
    }
    '/api/copier/links/$id/preview': {
      id: '/api/copier/links/$id/preview'
      path: '/preview'
      fullPath: '/api/copier/links/$id/preview'
      preLoaderRoute: typeof ApiCopierLinksIdPreviewRouteImport
      parentRoute: typeof ApiCopierLinksIdRoute
    }
    '/api/brokers/$id/clients/$login/positions': {
      id: '/api/brokers/$id/clients/$login/positions'
      path: '/positions'
      fullPath: '/api/brokers/$id/clients/$login/positions'
      preLoaderRoute: typeof ApiBrokersIdClientsLoginPositionsRouteImport
      parentRoute: typeof ApiBrokersIdClientsLoginRoute
    }
  }
}

interface ApiBrokersIdClientsLoginRouteChildren {
  ApiBrokersIdClientsLoginPositionsRoute: typeof ApiBrokersIdClientsLoginPositionsRoute
}

const ApiBrokersIdClientsLoginRouteChildren: ApiBrokersIdClientsLoginRouteChildren =
  {
    ApiBrokersIdClientsLoginPositionsRoute:
      ApiBrokersIdClientsLoginPositionsRoute,
  }

const ApiBrokersIdClientsLoginRouteWithChildren =
  ApiBrokersIdClientsLoginRoute._addFileChildren(
    ApiBrokersIdClientsLoginRouteChildren,
  )

interface ApiBrokersIdRouteChildren {
  ApiBrokersIdStatusRoute: typeof ApiBrokersIdStatusRoute
  ApiBrokersIdTestConnectionRoute: typeof ApiBrokersIdTestConnectionRoute
  ApiBrokersIdClientsLoginRoute: typeof ApiBrokersIdClientsLoginRouteWithChildren
  ApiBrokersIdClientsSearchRoute: typeof ApiBrokersIdClientsSearchRoute
}

const ApiBrokersIdRouteChildren: ApiBrokersIdRouteChildren = {
  ApiBrokersIdStatusRoute: ApiBrokersIdStatusRoute,
  ApiBrokersIdTestConnectionRoute: ApiBrokersIdTestConnectionRoute,
  ApiBrokersIdClientsLoginRoute: ApiBrokersIdClientsLoginRouteWithChildren,
  ApiBrokersIdClientsSearchRoute: ApiBrokersIdClientsSearchRoute,
}

const ApiBrokersIdRouteWithChildren = ApiBrokersIdRoute._addFileChildren(
  ApiBrokersIdRouteChildren,
)

interface ApiBrokersRouteChildren {
  ApiBrokersIdRoute: typeof ApiBrokersIdRouteWithChildren
}

const ApiBrokersRouteChildren: ApiBrokersRouteChildren = {
  ApiBrokersIdRoute: ApiBrokersIdRouteWithChildren,
}

const ApiBrokersRouteWithChildren = ApiBrokersRoute._addFileChildren(
  ApiBrokersRouteChildren,
)

interface ApiCopierAccountsIdRouteChildren {
  ApiCopierAccountsIdProbeRoute: typeof ApiCopierAccountsIdProbeRoute
  ApiCopierAccountsIdSymbolsRoute: typeof ApiCopierAccountsIdSymbolsRoute
}

const ApiCopierAccountsIdRouteChildren: ApiCopierAccountsIdRouteChildren = {
  ApiCopierAccountsIdProbeRoute: ApiCopierAccountsIdProbeRoute,
  ApiCopierAccountsIdSymbolsRoute: ApiCopierAccountsIdSymbolsRoute,
}

const ApiCopierAccountsIdRouteWithChildren =
  ApiCopierAccountsIdRoute._addFileChildren(ApiCopierAccountsIdRouteChildren)

interface ApiCopierAccountsRouteChildren {
  ApiCopierAccountsIdRoute: typeof ApiCopierAccountsIdRouteWithChildren
}

const ApiCopierAccountsRouteChildren: ApiCopierAccountsRouteChildren = {
  ApiCopierAccountsIdRoute: ApiCopierAccountsIdRouteWithChildren,
}

const ApiCopierAccountsRouteWithChildren =
  ApiCopierAccountsRoute._addFileChildren(ApiCopierAccountsRouteChildren)

interface ApiCopierLinksIdRouteChildren {
  ApiCopierLinksIdArmRoute: typeof ApiCopierLinksIdArmRoute
  ApiCopierLinksIdFlattenRoute: typeof ApiCopierLinksIdFlattenRoute
  ApiCopierLinksIdPreviewRoute: typeof ApiCopierLinksIdPreviewRoute
}

const ApiCopierLinksIdRouteChildren: ApiCopierLinksIdRouteChildren = {
  ApiCopierLinksIdArmRoute: ApiCopierLinksIdArmRoute,
  ApiCopierLinksIdFlattenRoute: ApiCopierLinksIdFlattenRoute,
  ApiCopierLinksIdPreviewRoute: ApiCopierLinksIdPreviewRoute,
}

const ApiCopierLinksIdRouteWithChildren =
  ApiCopierLinksIdRoute._addFileChildren(ApiCopierLinksIdRouteChildren)

interface ApiCopierLinksRouteChildren {
  ApiCopierLinksIdRoute: typeof ApiCopierLinksIdRouteWithChildren
}

const ApiCopierLinksRouteChildren: ApiCopierLinksRouteChildren = {
  ApiCopierLinksIdRoute: ApiCopierLinksIdRouteWithChildren,
}

const ApiCopierLinksRouteWithChildren = ApiCopierLinksRoute._addFileChildren(
  ApiCopierLinksRouteChildren,
)

interface ApiCopierRouteChildren {
  ApiCopierAccountsRoute: typeof ApiCopierAccountsRouteWithChildren
  ApiCopierLinksRoute: typeof ApiCopierLinksRouteWithChildren
}

const ApiCopierRouteChildren: ApiCopierRouteChildren = {
  ApiCopierAccountsRoute: ApiCopierAccountsRouteWithChildren,
  ApiCopierLinksRoute: ApiCopierLinksRouteWithChildren,
}

const ApiCopierRouteWithChildren = ApiCopierRoute._addFileChildren(
  ApiCopierRouteChildren,
)

interface ApiNotificationsRouteChildren {
  ApiNotificationsTestTelegramRoute: typeof ApiNotificationsTestTelegramRoute
}

const ApiNotificationsRouteChildren: ApiNotificationsRouteChildren = {
  ApiNotificationsTestTelegramRoute: ApiNotificationsTestTelegramRoute,
}

const ApiNotificationsRouteWithChildren =
  ApiNotificationsRoute._addFileChildren(ApiNotificationsRouteChildren)

interface ApiAdminUsersIdRouteChildren {
  ApiAdminUsersIdLimitsRoute: typeof ApiAdminUsersIdLimitsRoute
  ApiAdminUsersIdPermissionsRoute: typeof ApiAdminUsersIdPermissionsRoute
  ApiAdminUsersIdStatusRoute: typeof ApiAdminUsersIdStatusRoute
}

const ApiAdminUsersIdRouteChildren: ApiAdminUsersIdRouteChildren = {
  ApiAdminUsersIdLimitsRoute: ApiAdminUsersIdLimitsRoute,
  ApiAdminUsersIdPermissionsRoute: ApiAdminUsersIdPermissionsRoute,
  ApiAdminUsersIdStatusRoute: ApiAdminUsersIdStatusRoute,
}

const ApiAdminUsersIdRouteWithChildren = ApiAdminUsersIdRoute._addFileChildren(
  ApiAdminUsersIdRouteChildren,
)

interface ApiAdminUsersRouteChildren {
  ApiAdminUsersIdRoute: typeof ApiAdminUsersIdRouteWithChildren
}

const ApiAdminUsersRouteChildren: ApiAdminUsersRouteChildren = {
  ApiAdminUsersIdRoute: ApiAdminUsersIdRouteWithChildren,
}

const ApiAdminUsersRouteWithChildren = ApiAdminUsersRoute._addFileChildren(
  ApiAdminUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrokersRoute: BrokersRoute,
  CopierRoute: CopierRoute,
  DashboardRoute: DashboardRoute,
  MonitoredRoute: MonitoredRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminBrokersRoute: AdminBrokersRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMonitoredRoute: AdminMonitoredRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  ApiBrokersRoute: ApiBrokersRouteWithChildren,
  ApiCopierRoute: ApiCopierRouteWithChildren,
  ApiMonitoredRoute: ApiMonitoredRoute,
  ApiNotificationsRoute: ApiNotificationsRouteWithChildren,
  ApiSessionRoute: ApiSessionRoute,
  ClientLoginRoute: ClientLoginRoute,
  NotificationsIdRoute: NotificationsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  ApiAdminBrokersRoute: ApiAdminBrokersRoute,
  ApiAdminLogsRoute: ApiAdminLogsRoute,
  ApiAdminMonitoredRoute: ApiAdminMonitoredRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRouteWithChildren,
  ApiAlertsPollRoute: ApiAlertsPollRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
